project:
  type: website

website:
  title: "Data Science Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sabrinamichl
      - icon: twitter
        href: https://twitter.com
      - icon: linkedin
        href: https://www.linkedin.com/in/sabrina-michl-46650b231/
format:
  html:
    theme: minty
    css: styles.css

editor: visual

